CREATE TABLE IF NOT EXISTS foundation.dim_customer (
    customer_key      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       TEXT NOT NULL UNIQUE,
    customer_since    DATE,
    first_order_date  DATE,
    last_order_date   DATE
);
